### PR TITLE
fix: Port to optparse-applicative 0.18

### LINKED ISSUE #36: Fails to build with ghc-9.6 stackage nightly
```
       Building executable 'enigma' for crypto-enigma-0.1.1.6..                                                                     
       [5 of 5] Compiling Main                                                                                                      
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/crypto-enigma-0.1.1.6-46908301d69291f67e5252bb1bc7f62f7531ba44f95fc48f8846ada924231776
/cli/enigma.hs:5:42: error:                                                                                                         
           Module ‘Options.Applicative.Help.Pretty’ does not export ‘string’                                                        
         |                                                                                                                          
       5 | import Options.Applicative.Help.Pretty  (string)        -- Necessary to format help text -- https://github.com/pcapriotti
/optparse-applicative/issues/90#issuecomment-49868254                                                                               
         |                                          ^^^^^^
```

### PR DESCRIPTION
**Pull request by Vekhir**
@orome
After one and a half years, I've cycled back to this package. This PR closes #36.

Tested on Arch.

### CODE REVIEW

**Comment by orome** [comment]
@Vekhir Thanks! I've been off on other things for a while and will (eventually) get back to this of review and merge (and generally bringing this back up to stuff).
